name: deploy on masterp push
on:
  push:
    branches: [master]
    # paths-ignore:
    # - ".github/**"
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
        run: |
          ls -la
          mkdir -p dist
          cp -r ./app/. ./dist
          rm -r ./dist/sass
          npx netlify-cli deploy --dir=./dist --prod